import { LeagueLocations } from './league-locations.model';
import { LeagueTask } from "./league-tasks.model";

export const LeagueTaskArrayEasy: LeagueTask[] = [
{ id: 1, name: "Queen of Thieves", task: "Complete the quest \"Queen of Thieves\".", skills: {other: "See quest page."}, location: null },
{ id: 2, name: "Forsaken Tower", task: "Complete the quest \"Forsaken Tower\".", skills: {other: "See quest page."}, location: null },
{ id: 3, name: "Ascent of Arceuus", task: "Complete the quest \"Ascent of Arceuus\".", skills: {other: "See quest page."}, location: null },
{ id: 4, name: "250 Total Level", task: "Reach a total level of 250.", skills: { overall: 250 }, location: null },
{ id: 5, name: "500 Total Level", task: "Reach a total level of 500.", skills: { overall: 500}, location: null },
{ id: 6, name: "750 Total Level", task: "Reach a total level of 750.", skills: { overall: 750 }, location: null },
{ id: 7, name: "Base Level 10", task: "Reach a minimum of level 10 across all of your skills.", skills: {}, location: null },
{ id: 8, name: "Base Level 20", task: "Reach a minimum of level 20 across all of your skills.", skills: {}, location: null },
{ id: 9, name: "Base Level 30", task: "Reach a minimum of level 30 across all of your skills.", skills: {}, location: null },
{ id: 10, name: "Level 20 Attack", task: "Reach level 20 in your Attack skill.", skills: {attack: 20}, location: null },
{ id: 11, name: "Level 20 Strength", task: "Reach level 20 in your Strength skill.", skills: {strength: 20}, location: null },
{ id: 12, name: "Level 20 Defence", task: "Reach level 20 in your Defence skill.", skills: {defence: 20}, location: null },
{ id: 13, name: "Level 20 Ranged", task: "Reach level 20 in your Ranged skill.", skills: {ranged: 20}, location: null },
{ id: 14, name: "Level 20 Prayer", task: "Reach level 20 in your Prayer skill.", skills: {prayer: 20}, location: null },
{ id: 15, name: "Level 20 Magic", task: "Reach level 20 in your Magic skill.", skills: {magic: 20}, location: null },
{ id: 16, name: "Level 20 Runecraft", task: "Reach level 20 in your Runecraft skill.", skills: {runecraft: 20}, location: null },
{ id: 17, name: "Level 20 Construction", task: "Reach level 20 in your Construction skill.", skills: {construction: 20}, location: null },
{ id: 18, name: "Level 20 Hitpoints", task: "Reach level 20 in your Hitpoints skill.", skills: {hitpoints: 20}, location: null },
{ id: 19, name: "Level 20 Agility", task: "Reach level 20 in your Agility skill.", skills: {agility: 20}, location: null },
{ id: 20, name: "Level 20 Herblore", task: "Reach level 20 in your Herblore skill.", skills: {herblore: 20}, location: null },
{ id: 21, name: "Level 20 Thieving", task: "Reach level 20 in your Thieving skill.", skills: {thieving: 20}, location: null },
{ id: 22, name: "Level 20 Crafting", task: "Reach level 20 in your Crafting skill.", skills: {crafting: 20}, location: null },
{ id: 23, name: "Level 20 Fletching", task: "Reach level 20 in your Fletching skill.", skills: {fletching: 20}, location: null },
{ id: 24, name: "Level 20 Slayer", task: "Reach level 20 in your Slayer skill.", skills: {slayer: 20}, location: null },
{ id: 25, name: "Level 20 Hunter", task: "Reach level 20 in your Hunter skill.", skills: {hunter: 20}, location: null },
{ id: 26, name: "Level 20 Mining", task: "Reach level 20 in your Mining skill.", skills: {mining: 20}, location: null },
{ id: 27, name: "Level 20 Smithing", task: "Reach level 20 in your Smithing skill.", skills: {smithing: 20}, location: null },
{ id: 28, name: "Level 20 Fishing", task: "Reach level 20 in your Fishing skill.", skills: {fishing: 20}, location: null },
{ id: 29, name: "Level 20 Cooking", task: "Reach level 20 in your Cooking skill.", skills: {cooking: 20}, location: null },
{ id: 30, name: "Level 20 Firemaking", task: "Reach level 20 in your Firemaking skill.", skills: {firemaking: 20}, location: null },
{ id: 31, name: "Level 20 Woodcutting", task: "Reach level 20 in your Woodcutting skill.", skills: {woodcutting: 20}, location: null },
{ id: 32, name: "Level 20 Farming", task: "Reach level 20 in your Farming skill.", skills: {farming: 20}, location: null },
{ id: 33, name: "1 Wintertodt Kill", task: "Help the pyromancers subdue the Wintertodt.", skills: {firemaking: 50}, location: null },
{ id: 34, name: "25 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 25 times.", skills: {firemaking: 50}, location: null },
{ id: 35, name: "50 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 50 times.", skills: {firemaking: 50}, location: null },
{ id: 36, name: "75 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 75 times.", skills: {firemaking: 50}, location: null },
{ id: 37, name: "100 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 100 times.", skills: {firemaking: 50}, location: null },
{ id: 38, name: "Complete 1 Farming Contract", task: "Complete a farming contract for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 39, name: "10 Slayer Tasks", task: "Receive and complete a total of 10 slayer tasks.", skills: {}, location: null },
{ id: 40, name: "25 Slayer Tasks", task: "Receive and complete a total of 25 slayer tasks.", skills: {}, location: null },
{ id: 41, name: "50 Slayer Tasks", task: "Receive and complete a total of 50 slayer tasks.", skills: {}, location: null },
{ id: 42, name: "Friend of House Hosidius", task: "Achieve 100% favour with the Hosidius house.", skills: {}, location: null },
{ id: 43, name: "Friend of House Shayzien", task: "Achieve 100% favour with the Shayzien house.", skills: {}, location: null },
{ id: 44, name: "Friend of House Arceuus", task: "Achieve 100% favour with the Arceuus house.", skills: {}, location: null },
{ id: 45, name: "Friend of House Lovakengj", task: "Achieve 100% favour with the Lovakengj house.", skills: {}, location: null },
{ id: 46, name: "Friend of House piscarilius[sic]", task: "Achieve 100% favour with the piscarilius[sic] house.", skills: {}, location: null },
{ id: 47, name: "Steal a Golovanova Fruit Top", task: "Steal a Golovanova fruit top from a fruit stall in Hosidius.", skills: {thieving: 25}, location: null },
{ id: 48, name: "Complete a Sulphur Lizard Task", task: "Receive and complete a Sulphur Lizard slayer task.", skills: {slayer: 44}, location: null },
{ id: 49, name: "Complete a Troll Task", task: "Receive and complete a Troll slayer task.", skills: {slayer: 1}, location: null },
{ id: 50, name: "Complete a Temple Spider Task", task: "Receive and complete a Temple Spider slayer task.", skills: {slayer: 1}, location: null },
{ id: 51, name: "Complete a Banshee Task", task: "Receive and complete a Banshee slayer task.", skills: {slayer: 15}, location: null },
{ id: 52, name: "Complete a Lizardman Task", task: "Receive and complete a Lizardman slayer task.", skills: {slayer: 1}, location: null },
{ id: 53, name: "Complete a Greater Demon Task", task: "Receive and complete a Greater Demon slayer task.", skills: {slayer: 1}, location: null },
{ id: 54, name: "Complete a Fire Giant Task", task: "Receive and complete a Fire Giant slayer task.", skills: {slayer: 1}, location: null },
{ id: 55, name: "Complete a Moss Giant Task", task: "Receive and complete a Moss Giant slayer task.", skills: {slayer: 1}, location: null },
{ id: 56, name: "Complete a Jelly Task", task: "Receive and complete a Jelly slayer task.", skills: {slayer: 15}, location: null },
{ id: 57, name: "Complete a Metal Dragon Task", task: "Receive and complete a Bronze Dragon, Iron Dragon or Steel Dragon slayer task.", skills: {slayer: 1}, location: null },
{ id: 58, name: "1 Superior Slayer Encounter", task: "Defeat a superior foe while on a slayer task.", skills: {slayer: 15}, location: null },
{ id: 59, name: "Kourend and Kebos Easy Diary Tasks", task: "Complete all tasks in the easy tier of the Kourend and Kebos achievement diary.", skills: {}, location: null },
{ id: 60, name: "Open 1 Grubby Chest", task: "Open the grubby chest in the Forthos Dungeon.", skills: {thieving: 49}, location: null },
{ id: 61, name: "Steal 1 Artefact", task: "Steal an artefact for Captain Khaled, in Piscarilius.", skills: {thieving: 49}, location: null },
{ id: 62, name: "Steal 10 Artefacts", task: "Steal 10 artefacts for Captain Khaled, in Piscarilius.", skills: {thieving: 49}, location: null },
{ id: 63, name: "Turn in 1 Library Book", task: "Find and turn in a book in the Arceuus Library.", skills: {}, location: null },
{ id: 64, name: "Turn in 10 Library Books", task: "Find and turn in 10 books in the Arceuus Library.", skills: {}, location: null },
{ id: 65, name: "Turn in 25 Library Books", task: "Find and turn in 25 books in the Arceuus Library.", skills: {}, location: null },
{ id: 66, name: "Turn in 50 Library Books", task: "Find and turn in 50 books in the Arceuus Library.", skills: {}, location: null },
{ id: 67, name: "Turn in 100 Library Books", task: "Find and turn in 100 books in the Arceuus Library.", skills: {}, location: null },
{ id: 68, name: "1 Easy Clue Scroll", task: "Open a reward casket for completing an easy clue scroll.", skills: {}, location: null },
{ id: 69, name: "10 Easy Clue Scrolls", task: "Open 10 reward caskets for completing easy clue scrolls.", skills: {}, location: null },
{ id: 70, name: "1 Medium Clue Scroll", task: "Open a reward casket for completing a medium clue scroll.", skills: {}, location: null },
{ id: 71, name: "Enter Level 3 of the Chasm of Fire", task: "Enter the 3rd level of the Chasm of Fire in Shayzien.", skills: {}, location: null },
{ id: 72, name: "Receive a Konar Slayer Task", task: "Have a slayer task assigned by Konar.", skills: {}, location: null },
{ id: 73, name: "Bank at Land's End", task: "Open your bank using the bank at Land's End.", skills: {}, location: null },
{ id: 74, name: "Bank at Mount Quidamortem", task: "Open your bank using the bank at Mount Quidamortem.", skills: {}, location: null },
{ id: 75, name: "Travel to Molch Island", task: "Take one of the boats around Lake Molch to Molch Island.", skills: {}, location: null },
{ id: 76, name: "Equip Tier 5 Shayzien Armour", task: "Equip a full set of tier 5 Shayzien armour.", skills: {defence: 20}, location: null },
{ id: 77, name: "Unlock All Catacombs Entrances", task: "Unlock all entrances to the Catacombs of Kourend, around the kingdom.", skills: {}, location: null },
{ id: 78, name: "Complete 25 Farming Contracts", task: "Complete 25 farming contracts for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 79, name: "Complete 50 Farming Contracts", task: "Complete 50 farming contracts for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 80, name: "Complete 75 Farming Contracts", task: "Complete 75 farming contracts for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 81, name: "Complete 100 Farming Contracts", task: "Complete 100 farming contracts for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 82, name: "Complete an Undead Druid Task", task: "Receive and complete an Undead Druid slayer task.", skills: {slayer: 1}, location: null },
{ id: 83, name: "Complete an Aberrant Spectre Task", task: "Receive and complete an Aberrant Spectre slayer task.", skills: {slayer: 60}, location: null },
{ id: 84, name: "Complete a Bloodveld Task", task: "Receive and complete a Bloodveld slayer task.", skills: {slayer: 50}, location: null },
{ id: 85, name: "Complete a Dust Devil Task", task: "Receive and complete a Dust Devil slayer task.", skills: {slayer: 65}, location: null },
{ id: 86, name: "Complete a Wyrm Task", task: "Receive and complete a Wyrm slayer task.", skills: {slayer: 62}, location: null },
{ id: 87, name: "1 Sarachnis Kill", task: "Kill Sarachnis in the Forthos Dungeon.", skills: {}, location: null },
  ];

  export const LeagueTaskArrayMedium: LeagueTask[] = [
    { id: 1000, name: "1000 Total Level", task: "Reach a total level of 1000.", skills: { overall: 1000 }, location: null },
    { id: 1001, name: "Enter the Woodcutting Guild", task: "Enter the Woodcutting Guild in Hosidius.", skills: { woodcutting: 60 }, location: LeagueLocations.Zeah },
    { id: 1002, name: "Open 50 Grubby Chests", task: "Open the grubby chest in the Forthos Dungeon 50 times.", skills: { thieving: 57 }, location: LeagueLocations.Zeah },
    { id: 1003, name: "Complete a Nechryael Task", task: "Receive and complete a Nechryael slayer task.", skills: { slayer: 77 }, location: LeagueLocations.Morytania },
    { id: 1004, name: "Purchase Gricoller's Can", task: "Purchase Gricoller's can from the Tithe Farm minigame.", skills: { farming: 34 }, location: LeagueLocations.Zeah }
  ];

  export const LeagueTaskArrayHard: LeagueTask[] = [
    { id: 2000, name: "Equip a Mist Battlestaff", task: "Obtain and equip a Mist battlestaff.", skills: { attack: 30, magic: 30 }, location: null },
    { id: 2001, name: "Equip the Angler's Outfit", task: "Equip a full set of the angler's outfit, purchased from Alry on Molch Island.", skills: { hunter: 35, fishing: 43 }, location: LeagueLocations.Zeah },
    { id: 2002, name: "Equip Boots of Brimstone", task: "Obtain and equip a pair of Boots of brimstone.", skills: { slayer: 84, defence: 70, magic: 70, ranged: 70 }, location: null },
    { id: 2003, name: "Equip a Dragonfire Shield", task: "Obtain and equip a Dragonfire shield.", skills: { defence: 75, smithing: 90 }, location: null },
    { id: 2004, name: "Cast Resurrect Crops", task: "Cast the spell Resurrect Crops from the Arceuus spellbook.", skills: { magic: 78 }, location: null }
  ];

  export const LeagueTaskArrayElite: LeagueTask[] = [
    { id: 3000, name: "2000 Total Level", task: "Reach a total level of 2000.", skills: { overall: 2000 }, location: null },
    { id: 3001, name: "Equip an Eternal Slayer Ring", task: "Craft and equip an Eternal slayer ring.", skills: { crafting: 75 }, location: null },
    { id: 3002, name: "Equip an Dragon Hunter Lance", task: "Obtain and equip a Dragon Huntert Lance.", skills: { attack: 70, slayer: 95 }, location: null }
  ];

  export const LeagueTaskArrayMaster: LeagueTask[] = [
    { id: 4000, name: "2277 Total Level", task: "Reach a total level of 2277.", skills: { overall: 2277 }, location: null },
    { id: 4001, name: "Equip a Golden Tench", task: "Equip a Golden tench, caught by aerial fishing on Molch Island.", skills: { hunter: 35, fishing: 43 }, location: null },
    { id: 4002, name: "Equip a Kodai Wand", task: "Obtain and equip a Kodai wand.", skills: { magic: 75 }, location: null }
  ];