import { LeagueLocations } from './league-locations.model';
import { LeagueTask } from "./league-tasks.model";

export const LeagueTaskArrayEasy: LeagueTask[] = [
{ id: 1, name: "Queen of Thieves", task: "Complete the quest \"Queen of Thieves\".", skills: {other: "See quest page."}, location: null },
{ id: 2, name: "Forsaken Tower", task: "Complete the quest \"Forsaken Tower\".", skills: {other: "See quest page."}, location: null },
{ id: 3, name: "Ascent of Arceuus", task: "Complete the quest \"Ascent of Arceuus\".", skills: {other: "See quest page."}, location: null },
{ id: 4, name: "250 Total Level", task: "Reach a total level of 250.", skills: { overall: 250 }, location: null },
{ id: 5, name: "500 Total Level", task: "Reach a total level of 500.", skills: { overall: 500}, location: null },
{ id: 6, name: "750 Total Level", task: "Reach a total level of 750.", skills: { overall: 750 }, location: null },
{ id: 7, name: "Base Level 10", task: "Reach a minimum of level 10 across all of your skills.", skills: {}, location: null },
{ id: 8, name: "Base Level 20", task: "Reach a minimum of level 20 across all of your skills.", skills: {}, location: null },
{ id: 9, name: "Base Level 30", task: "Reach a minimum of level 30 across all of your skills.", skills: {}, location: null },
{ id: 10, name: "Level 20 Attack", task: "Reach level 20 in your Attack skill.", skills: {attack: 20}, location: null },
{ id: 11, name: "Level 20 Strength", task: "Reach level 20 in your Strength skill.", skills: {strength: 20}, location: null },
{ id: 12, name: "Level 20 Defence", task: "Reach level 20 in your Defence skill.", skills: {defence: 20}, location: null },
{ id: 13, name: "Level 20 Ranged", task: "Reach level 20 in your Ranged skill.", skills: {ranged: 20}, location: null },
{ id: 14, name: "Level 20 Prayer", task: "Reach level 20 in your Prayer skill.", skills: {prayer: 20}, location: null },
{ id: 15, name: "Level 20 Magic", task: "Reach level 20 in your Magic skill.", skills: {magic: 20}, location: null },
{ id: 16, name: "Level 20 Runecraft", task: "Reach level 20 in your Runecraft skill.", skills: {runecraft: 20}, location: null },
{ id: 17, name: "Level 20 Construction", task: "Reach level 20 in your Construction skill.", skills: {construction: 20}, location: null },
{ id: 18, name: "Level 20 Hitpoints", task: "Reach level 20 in your Hitpoints skill.", skills: {hitpoints: 20}, location: null },
{ id: 19, name: "Level 20 Agility", task: "Reach level 20 in your Agility skill.", skills: {agility: 20}, location: null },
{ id: 20, name: "Level 20 Herblore", task: "Reach level 20 in your Herblore skill.", skills: {herblore: 20}, location: null },
{ id: 21, name: "Level 20 Thieving", task: "Reach level 20 in your Thieving skill.", skills: {thieving: 20}, location: null },
{ id: 22, name: "Level 20 Crafting", task: "Reach level 20 in your Crafting skill.", skills: {crafting: 20}, location: null },
{ id: 23, name: "Level 20 Fletching", task: "Reach level 20 in your Fletching skill.", skills: {fletching: 20}, location: null },
{ id: 24, name: "Level 20 Slayer", task: "Reach level 20 in your Slayer skill.", skills: {slayer: 20}, location: null },
{ id: 25, name: "Level 20 Hunter", task: "Reach level 20 in your Hunter skill.", skills: {hunter: 20}, location: null },
{ id: 26, name: "Level 20 Mining", task: "Reach level 20 in your Mining skill.", skills: {mining: 20}, location: null },
{ id: 27, name: "Level 20 Smithing", task: "Reach level 20 in your Smithing skill.", skills: {smithing: 20}, location: null },
{ id: 28, name: "Level 20 Fishing", task: "Reach level 20 in your Fishing skill.", skills: {fishing: 20}, location: null },
{ id: 29, name: "Level 20 Cooking", task: "Reach level 20 in your Cooking skill.", skills: {cooking: 20}, location: null },
{ id: 30, name: "Level 20 Firemaking", task: "Reach level 20 in your Firemaking skill.", skills: {firemaking: 20}, location: null },
{ id: 31, name: "Level 20 Woodcutting", task: "Reach level 20 in your Woodcutting skill.", skills: {woodcutting: 20}, location: null },
{ id: 32, name: "Level 20 Farming", task: "Reach level 20 in your Farming skill.", skills: {farming: 20}, location: null },
{ id: 33, name: "1 Wintertodt Kill", task: "Help the pyromancers subdue the Wintertodt.", skills: {firemaking: 50}, location: null },
{ id: 34, name: "25 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 25 times.", skills: {firemaking: 50}, location: null },
{ id: 35, name: "50 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 50 times.", skills: {firemaking: 50}, location: null },
{ id: 36, name: "75 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 75 times.", skills: {firemaking: 50}, location: null },
{ id: 37, name: "100 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 100 times.", skills: {firemaking: 50}, location: null },
{ id: 38, name: "Complete 1 Farming Contract", task: "Complete a farming contract for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 39, name: "10 Slayer Tasks", task: "Receive and complete a total of 10 slayer tasks.", skills: {}, location: null },
{ id: 40, name: "25 Slayer Tasks", task: "Receive and complete a total of 25 slayer tasks.", skills: {}, location: null },
{ id: 41, name: "50 Slayer Tasks", task: "Receive and complete a total of 50 slayer tasks.", skills: {}, location: null },
{ id: 42, name: "Friend of House Hosidius", task: "Achieve 100% favour with the Hosidius house.", skills: {}, location: null },
{ id: 43, name: "Friend of House Shayzien", task: "Achieve 100% favour with the Shayzien house.", skills: {}, location: null },
{ id: 44, name: "Friend of House Arceuus", task: "Achieve 100% favour with the Arceuus house.", skills: {}, location: null },
{ id: 45, name: "Friend of House Lovakengj", task: "Achieve 100% favour with the Lovakengj house.", skills: {}, location: null },
{ id: 46, name: "Friend of House piscarilius[sic]", task: "Achieve 100% favour with the piscarilius[sic] house.", skills: {}, location: null },
{ id: 47, name: "Steal a Golovanova Fruit Top", task: "Steal a Golovanova fruit top from a fruit stall in Hosidius.", skills: {thieving: 25}, location: null },
{ id: 48, name: "Complete a Sulphur Lizard Task", task: "Receive and complete a Sulphur Lizard slayer task.", skills: {slayer: 44}, location: null },
{ id: 49, name: "Complete a Troll Task", task: "Receive and complete a Troll slayer task.", skills: {slayer: 1}, location: null },
{ id: 50, name: "Complete a Temple Spider Task", task: "Receive and complete a Temple Spider slayer task.", skills: {slayer: 1}, location: null },
{ id: 51, name: "Complete a Banshee Task", task: "Receive and complete a Banshee slayer task.", skills: {slayer: 15}, location: null },
{ id: 52, name: "Complete a Lizardman Task", task: "Receive and complete a Lizardman slayer task.", skills: {slayer: 1}, location: null },
{ id: 53, name: "Complete a Greater Demon Task", task: "Receive and complete a Greater Demon slayer task.", skills: {slayer: 1}, location: null },
{ id: 54, name: "Complete a Fire Giant Task", task: "Receive and complete a Fire Giant slayer task.", skills: {slayer: 1}, location: null },
{ id: 55, name: "Complete a Moss Giant Task", task: "Receive and complete a Moss Giant slayer task.", skills: {slayer: 1}, location: null },
{ id: 56, name: "Complete a Jelly Task", task: "Receive and complete a Jelly slayer task.", skills: {slayer: 15}, location: null },
{ id: 57, name: "Complete a Metal Dragon Task", task: "Receive and complete a Bronze Dragon, Iron Dragon or Steel Dragon slayer task.", skills: {slayer: 1}, location: null },
{ id: 58, name: "1 Superior Slayer Encounter", task: "Defeat a superior foe while on a slayer task.", skills: {slayer: 15}, location: null },
{ id: 59, name: "Kourend and Kebos Easy Diary Tasks", task: "Complete all tasks in the easy tier of the Kourend and Kebos achievement diary.", skills: {}, location: null },
{ id: 60, name: "Open 1 Grubby Chest", task: "Open the grubby chest in the Forthos Dungeon.", skills: {thieving: 49}, location: null },
{ id: 61, name: "Steal 1 Artefact", task: "Steal an artefact for Captain Khaled, in Piscarilius.", skills: {thieving: 49}, location: null },
{ id: 62, name: "Steal 10 Artefacts", task: "Steal 10 artefacts for Captain Khaled, in Piscarilius.", skills: {thieving: 49}, location: null },
{ id: 63, name: "Turn in 1 Library Book", task: "Find and turn in a book in the Arceuus Library.", skills: {}, location: null },
{ id: 64, name: "Turn in 10 Library Books", task: "Find and turn in 10 books in the Arceuus Library.", skills: {}, location: null },
{ id: 65, name: "Turn in 25 Library Books", task: "Find and turn in 25 books in the Arceuus Library.", skills: {}, location: null },
{ id: 66, name: "Turn in 50 Library Books", task: "Find and turn in 50 books in the Arceuus Library.", skills: {}, location: null },
{ id: 67, name: "Turn in 100 Library Books", task: "Find and turn in 100 books in the Arceuus Library.", skills: {}, location: null },
{ id: 68, name: "1 Easy Clue Scroll", task: "Open a reward casket for completing an easy clue scroll.", skills: {}, location: null },
{ id: 69, name: "10 Easy Clue Scrolls", task: "Open 10 reward caskets for completing easy clue scrolls.", skills: {}, location: null },
{ id: 70, name: "1 Medium Clue Scroll", task: "Open a reward casket for completing a medium clue scroll.", skills: {}, location: null },
{ id: 71, name: "Enter Level 3 of the Chasm of Fire", task: "Enter the 3rd level of the Chasm of Fire in Shayzien.", skills: {}, location: null },
{ id: 72, name: "Receive a Konar Slayer Task", task: "Have a slayer task assigned by Konar.", skills: {}, location: null },
{ id: 73, name: "Bank at Land's End", task: "Open your bank using the bank at Land's End.", skills: {}, location: null },
{ id: 74, name: "Bank at Mount Quidamortem", task: "Open your bank using the bank at Mount Quidamortem.", skills: {}, location: null },
{ id: 75, name: "Travel to Molch Island", task: "Take one of the boats around Lake Molch to Molch Island.", skills: {}, location: null },
{ id: 76, name: "Equip Tier 5 Shayzien Armour", task: "Equip a full set of tier 5 Shayzien armour.", skills: {defence: 20}, location: null },
{ id: 77, name: "Unlock All Catacombs Entrances", task: "Unlock all entrances to the Catacombs of Kourend, around the kingdom.", skills: {}, location: null },
{ id: 78, name: "Complete 25 Farming Contracts", task: "Complete 25 farming contracts for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 79, name: "Complete 50 Farming Contracts", task: "Complete 50 farming contracts for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 80, name: "Complete 75 Farming Contracts", task: "Complete 75 farming contracts for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 81, name: "Complete 100 Farming Contracts", task: "Complete 100 farming contracts for Guildmaster Jane in the farming guild.", skills: {farming: 45}, location: null },
{ id: 82, name: "Complete an Undead Druid Task", task: "Receive and complete an Undead Druid slayer task.", skills: {slayer: 1}, location: null },
{ id: 83, name: "Complete an Aberrant Spectre Task", task: "Receive and complete an Aberrant Spectre slayer task.", skills: {slayer: 60}, location: null },
{ id: 84, name: "Complete a Bloodveld Task", task: "Receive and complete a Bloodveld slayer task.", skills: {slayer: 50}, location: null },
{ id: 85, name: "Complete a Dust Devil Task", task: "Receive and complete a Dust Devil slayer task.", skills: {slayer: 65}, location: null },
{ id: 86, name: "Complete a Wyrm Task", task: "Receive and complete a Wyrm slayer task.", skills: {slayer: 62}, location: null },
{ id: 87, name: "1 Sarachnis Kill", task: "Kill Sarachnis in the Forthos Dungeon.", skills: {}, location: null },
  ];

  export const LeagueTaskArrayMedium: LeagueTask[] = [
    { id: 1, name: "10 Superior Slayer Encounters", task: "Defeat 10 superior foes while on a slayer task.", skills: { slayer: 15 }, location: null },
    { id: 2, name: "25 Easy Clue Scrolls", task: "Open 25 reward caskets for completing easy clue scrolls.", skills: {  }, location: null },
    { id: 3, name: "50 Easy Clue Scrolls", task: "Open 50 reward caskets for completing easy clue scrolls.", skills: {  }, location: null },
    { id: 4, name: "100 Easy Clue Scrolls", task: "Open 100 reward caskets for completing easy clue scrolls.", skills: {  }, location: null },
    { id: 5, name: "10 Medium Clue Scrolls", task: "Open 10 reward caskets for completing medium clue scrolls.", skills: {  }, location: null },
    { id: 6, name: "25 Medium Clue Scrolls", task: "Open 25 reward caskets for completing medium clue scrolls.", skills: {  }, location: null },
    { id: 7, name: "50 Medium Clue Scrolls", task: "Open 50 reward caskets for completing medium clue scrolls.", skills: {  }, location: null },
    { id: 8, name: "1 Hard Clue Scroll", task: "Open a reward casket for completing a hard clue scroll.", skills: {  }, location: null },
    { id: 9, name: "10 Hard Clue Scrolls", task: "Open 10 reward caskets for completing hard clue scrolls.", skills: {  }, location: null },
    { id: 10, name: "1 Elite Clue Scroll", task: "Open a reward casket for completing an elite clue scroll.", skills: {  }, location: null },
    { id: 11, name: "Depths of Despair", task: "Complete the quest \"Depths of Despair\".", skills: { other: "See quest page" }, location: null },
    { id: 12, name: "Tale Of The Righteous", task: "Complete the quest \"Tale of the Righteous\".", skills: { other: "See quest page" }, location: null },
    { id: 13, name: "In Search Of Knowledge", task: "Complete the mini-quest \"In Search Of Knowledge\".", skills: { other: "See quest page" }, location: null },
    { id: 14, name: "Architectural Alliance", task: "Complete the mini-quest \"Architectural Alliance\".", skills: { other: "See quest page" }, location: null },
    { id: 15, name: "1000 Total Level", task: "Reach a total level of 1000.", skills: { overall: 1000 }, location: null },
    { id: 16, name: "1250 Total Level", task: "Reach a total level of 1250.", skills: { overall: 1250 }, location: null },
    { id: 17, name: "Base Level 40", task: "Reach a minimum of level 40 across all of your skills.", skills: { overall: 40 }, location: null },
    { id: 18, name: "Base Level 50", task: "Reach a minimum of level 50 across all of your skills.", skills: { overall: 50 }, location: null },
    { id: 19, name: "Level 40 Attack", task: "Reach level 40 in your Attack skill.", skills: { attack: 40 }, location: null },
    { id: 20, name: "Level 60 Attack", task: "Reach level 60 in your Attack skill.", skills: { attack: 60 }, location: null },
    { id: 21, name: "Level 40 Strength", task: "Reach level 40 in your Strength skill.", skills: { strength: 40 }, location: null },
    { id: 22, name: "Level 60 Strength", task: "Reach level 60 in your Strength skill.", skills: { strength: 60 }, location: null },
    { id: 23, name: "Level 40 Defence", task: "Reach level 40 in your Defence skill.", skills: { defence: 40 }, location: null },
    { id: 24, name: "Level 60 Defence", task: "Reach level 60 in your Defence skill.", skills: { defence: 60 }, location: null },
    { id: 25, name: "Level 40 Ranged", task: "Reach level 40 in your Ranged skill.", skills: { ranged: 40 }, location: null },
    { id: 26, name: "Level 60 Ranged", task: "Reach level 60 in your Ranged skill.", skills: { ranged: 60 }, location: null },
    { id: 27, name: "Level 40 Prayer", task: "Reach level 40 in your Prayer skill.", skills: { prayer: 40 }, location: null },
    { id: 28, name: "Level 60 Prayer", task: "Reach level 60 in your Prayer skill.", skills: { prayer: 60 }, location: null },
    { id: 29, name: "Level 40 Magic", task: "Reach level 40 in your Magic skill.", skills: { magic: 40 }, location: null },
    { id: 30, name: "Level 60 Magic", task: "Reach level 60 in your Magic skill.", skills: { magic: 60 }, location: null },
    { id: 31, name: "Level 40 Runecraft", task: "Reach level 40 in your Runecraft skill.", skills: { runecraft: 40 }, location: null },
    { id: 32, name: "Level 60 Runecraft", task: "Reach level 60 in your Runecraft skill.", skills: { runecraft: 60 }, location: null },
    { id: 33, name: "Level 40 Construction", task: "Reach level 40 in your Construction skill.", skills: { construction: 40 }, location: null },
    { id: 34, name: "Level 60 Construction", task: "Reach level 60 in your Construction skill.", skills: { construction: 60 }, location: null },
    { id: 35, name: "Level 40 Hitpoints", task: "Reach level 40 in your Hitpoints skill.", skills: { hitpoints: 40 }, location: null },
    { id: 36, name: "Level 60 Hitpoints", task: "Reach level 60 in your Hitpoints skill.", skills: { hitpoints: 60 }, location: null },
    { id: 37, name: "Level 40 Agility", task: "Reach level 40 in your Agility skill.", skills: { agility: 40 }, location: null },
    { id: 38, name: "Level 60 Agility", task: "Reach level 60 in your Agility skill.", skills: { agility: 60 }, location: null },
    { id: 39, name: "Level 40 Herblore", task: "Reach level 40 in your Herblore skill.", skills: { herblore: 40 }, location: null },
    { id: 40, name: "Level 60 Herblore", task: "Reach level 60 in your Herblore skill.", skills: { herblore: 60 }, location: null },
    { id: 41, name: "Level 40 Thieving", task: "Reach level 40 in your Thieving skill.", skills: { thieving: 40 }, location: null },
    { id: 42, name: "Level 60 Thieving", task: "Reach level 60 in your Thieving skill.", skills: { thieving: 60 }, location: null },
    { id: 43, name: "Level 40 Crafting", task: "Reach level 40 in your Crafting skill.", skills: { crafting: 40 }, location: null },
    { id: 44, name: "Level 60 Crafting", task: "Reach level 60 in your Crafting skill.", skills: { crafting: 60 }, location: null },
    { id: 45, name: "Level 40 Fletching", task: "Reach level 40 in your Fletching skill.", skills: { fletching: 40 }, location: null },
    { id: 46, name: "Level 60 Fletching", task: "Reach level 60 in your Fletching skill.", skills: { fletching: 60 }, location: null },
    { id: 47, name: "Level 40 Slayer", task: "Reach level 40 in your Slayer skill.", skills: { slayer: 40 }, location: null },
    { id: 48, name: "Level 60 Slayer", task: "Reach level 60 in your Slayer skill.", skills: { slayer: 60 }, location: null },
    { id: 49, name: "Level 40 Hunter", task: "Reach level 40 in your Hunter skill.", skills: { hunter: 40 }, location: null },
    { id: 50, name: "Level 60 Hunter", task: "Reach level 60 in your Hunter skill.", skills: { hunter: 60 }, location: null },
    { id: 51, name: "Level 40 Mining", task: "Reach level 40 in your Mining skill.", skills: { mining: 40 }, location: null },
    { id: 52, name: "Level 60 Mining", task: "Reach level 60 in your Mining skill.", skills: { mining: 60 }, location: null },
    { id: 53, name: "Level 40 Smithing", task: "Reach level 40 in your Smithing skill.", skills: { smithing: 40 }, location: null },
    { id: 54, name: "Level 60 Smithing", task: "Reach level 60 in your Smithing skill.", skills: { smithing: 60 }, location: null },
    { id: 55, name: "Level 40 Fishing", task: "Reach level 40 in your Fishing skill.", skills: { fishing: 40 }, location: null },
    { id: 56, name: "Level 60 Fishing", task: "Reach level 60 in your Fishing skill.", skills: { fishing: 60 }, location: null },
    { id: 57, name: "Level 40 Cooking", task: "Reach level 40 in your Cooking skill.", skills: { cooking: 40 }, location: null },
    { id: 58, name: "Level 60 Cooking", task: "Reach level 60 in your Cooking skill.", skills: { cooking: 60 }, location: null },
    { id: 59, name: "Level 40 Firemaking", task: "Reach level 40 in your Firemaking skill.", skills: { firemaking: 40 }, location: null },
    { id: 60, name: "Level 60 Firemaking", task: "Reach level 60 in your Firemaking skill.", skills: { firemaking: 60 }, location: null },
    { id: 61, name: "Level 40 Woodcutting", task: "Reach level 40 in your Woodcutting skill.", skills: { woodcutting: 40 }, location: null },
    { id: 62, name: "Level 60 Woodcutting", task: "Reach level 60 in your Woodcutting skill.", skills: { woodcutting: 60 }, location: null },
    { id: 63, name: "Level 40 Farming", task: "Reach level 40 in your Farming skill.", skills: { farming: 40 }, location: null },
    { id: 64, name: "Level 60 Farming", task: "Reach level 60 in your Farming skill.", skills: { farming: 60 }, location: null },
    { id: 65, name: "200 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 200 times.", skills: { firemaking: 50 }, location: null },
    { id: 66, name: "100 Slayer Tasks", task: "Receive and complete a total of 100 slayer tasks.", skills: { other: "5 Combat" }, location: null },
    { id: 67, name: "Plant 100 Golovanova Seeds", task: "Plant 100 Golovanova seeds in the Tithe Farm minigame.", skills: { farming: 34 }, location: null },
    { id: 68, name: "Enter the Farming Guild", task: "Enter the Farming Guild in the Kebos Lowlands.", skills: { farming: 45 }, location: null },
    { id: 69, name: "Serve 20 Stews in the Mess Hall", task: "Make and serve 20 stews in the Mess Hall in Hosidius. Note: This requires at least 30% appreciation.", skills: { cooking: 25 }, location: null },
    { id: 70, name: "Activate Smite", task: "Activate Smite in your prayer book.", skills: { prayer: 52 }, location: null },
    { id: 71, name: "Pickpocket a Master Farmer", task: "Successfully pickpocket from a master farmer.", skills: { thieving: 38 }, location: null },
    { id: 72, name: "Enter the Woodcutting Guild", task: "Enter the Woodcutting Guild in Hosidius.", skills: { woodcutting: 60 }, location: null },
    { id: 73, name: "Complete a Black Demon Task", task: "Receive and complete a Black Demon slayer task.", skills: { slayer: 1 }, location: null },
    { id: 74, name: "Complete a Hellhound Task", task: "Receive and complete a Hellhound slayer task.", skills: { slayer: 1 }, location: null },
    { id: 75, name: "Complete a Blue Dragon Task", task: "Receive and complete a Blue Dragon slayer task.", skills: { slayer: 1 }, location: null },
    { id: 76, name: "Complete a Red Dragon Task", task: "Receive and complete a Red Dragon slayer task.", skills: { slayer: 1 }, location: null },
    { id: 77, name: "25 Superior Slayer Encounters", task: "Defeat 25 superior foes while on a slayer task.", skills: { slayer: 15 }, location: null },
    { id: 78, name: "50 Superior Slayer Encounters", task: "Defeat 50 superior foes while on a slayer task.", skills: { slayer: 15 }, location: null },
    { id: 79, name: "75 Superior Slayer Encounters", task: "Defeat 75 superior foes while on a slayer task.", skills: { slayer: 15 }, location: null },
    { id: 80, name: "100 Superior Slayer Encounters", task: "Defeat 100 superior foes while on a slayer task.", skills: { slayer: 15 }, location: null },
    { id: 81, name: "100 Lizardmen Shaman Kills", task: "Help the Shayzien house by killing 100 Lizardmen shamans.", skills: { slayer: 1 }, location: null },
    { id: 82, name: "500 Lizardmen Shaman Kills", task: "Help the Shayzien house by killing 500 Lizardmen shamans.", skills: { slayer: 1 }, location: null },
    { id: 83, name: "25 Sarachnis Kills", task: "Kill Sarachnis in the Forthos Dungeon 25 times.", skills: {  }, location: null },
    { id: 84, name: "50 Sarachnis Kills", task: "Kill Sarachnis in the Forthos Dungeon 50 times.", skills: {  }, location: null },
    { id: 85, name: "75 Sarachnis Kills", task: "Kill Sarachnis in the Forthos Dungeon 75 times.", skills: {  }, location: null },
    { id: 86, name: "100 Sarachnis Kills", task: "Kill Sarachnis in the Forthos Dungeon 100 times.", skills: {  }, location: null },
    { id: 87, name: "1 Skotizo Kill", task: "Kill Skotizo beneath the Catacombs of Kourend.", skills: {  }, location: null },
    { id: 88, name: "Teleport to Xeric's Honour", task: "Teleport to Xeric's Honour, using Xeric's talisman.", skills: {  }, location: null },
    { id: 89, name: "Kourend and Kebos Medium Diary Tasks", task: "Complete all tasks in the medium tier of the Kourend and Kebos achievement diary.", skills: { other: "See here" }, location: null },
    { id: 90, name: "Open 10 Grubby Chests", task: "Open the grubby chest in the Forthos Dungeon 10 times.", skills: { thieving: 57 }, location: null },
    { id: 91, name: "Open 25 Grubby Chests", task: "Open the grubby chest in the Forthos Dungeon 25 times.", skills: { thieving: 57 }, location: null },
    { id: 92, name: "Open 50 Grubby Chests", task: "Open the grubby chest in the Forthos Dungeon 50 times.", skills: { thieving: 57 }, location: null },
    { id: 93, name: "Steal 25 Artefacts", task: "Steal 25 artefacts for Captain Khaled, in Piscarilius.", skills: { thieving: 49 }, location: null },
    { id: 94, name: "Steal 50 Artefacts", task: "Steal 50 artefacts for Captain Khaled, in Piscarilius.", skills: { thieving: 49 }, location: null },
    { id: 95, name: "Steal 100 Artefacts", task: "Steal 100 artefacts for Captain Khaled, in Piscarilius.", skills: { thieving: 49 }, location: null },
    { id: 96, name: "Equip Xeric's Talisman", task: "Obtain and equip Xeric's talisman.", skills: {  }, location: null },
    { id: 97, name: "Cast Kourend Castle Teleport", task: "Cast the spell Kourend Castle Teleport after unlocking it by reading transportation incantations.", skills: { magic: 69 }, location: null },
    { id: 98, name: "Obtain the Temple Key", task: "Obtain the Temple key in the Forthos Dungeon.", skills: {  }, location: null },
    { id: 99, name: "300 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 300 times.", skills: { firemaking: 50 }, location: null },
    { id: 100, name: "400 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 400 times.", skills: { firemaking: 50 }, location: null },
    { id: 101, name: "500 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 500 times.", skills: { firemaking: 50 }, location: null },
    { id: 102, name: "Complete 200 Farming Contracts", task: "Complete 200 farming contracts for Guildmaster Jane in the farming guild.", skills: { farming: 45 }, location: null },
    { id: 103, name: "Complete 300 Farming Contracts", task: "Complete 300 farming contracts for Guildmaster Jane in the farming guild.", skills: { farming: 45 }, location: null },
    { id: 104, name: "Complete 400 Farming Contracts", task: "Complete 400 farming contracts for Guildmaster Jane in the farming guild.", skills: { farming: 45 }, location: null },
    { id: 105, name: "Complete 500 Farming Contracts", task: "Complete 500 farming contracts for Guildmaster Jane in the farming guild.", skills: { farming: 45 }, location: null },
    { id: 106, name: "Complete a Brutal Black Dragon Task", task: "Receive and complete a Brutal Black Dragon slayer task.", skills: { slayer: 77 }, location: null },
    { id: 107, name: "Complete a Nechryael Task", task: "Receive and complete a Nechryael slayer task.", skills: { slayer: 80 }, location: null },
    { id: 108, name: "1000 Lizardmen Shaman Kills", task: "Help the Shayzien house by killing 1000 Lizardmen shamans.", skills: { slayer: 1 }, location: null },
    { id: 109, name: "250 Sarachnis Kills", task: "Kill Sarachnis in the Forthos Dungeon 250 times.", skills: {  }, location: null },
    { id: 110, name: "1 Alchemical Hydra Kill", task: "Kill the Alchemical Hydra in Mount Karuulm.", skills: { slayer: 95 }, location: null },
    { id: 111, name: "25 Alchemical Hydra Kills", task: "Kill the Alchemical Hydra in Mount Karuulm 25 times.", skills: { slayer: 95 }, location: null },
    { id: 112, name: "50 Alchemical Hydra Kills", task: "Kill the Alchemical Hydra in Mount Karuulm 50 times.", skills: { slayer: 95 }, location: null },
    { id: 113, name: "75 Alchemical Hydra Kills", task: "Kill the Alchemical Hydra in Mount Karuulm 75 times.", skills: { slayer: 95 }, location: null },
    { id: 114, name: "100 Alchemical Hydra Kills", task: "Kill the Alchemical Hydra in Mount Karuulm 100 times.", skills: { slayer: 95 }, location: null },
    { id: 115, name: "Turn in 250 Library Books", task: "Find and turn in 250 books in the Arceuus Library.", skills: {  }, location: null },
    { id: 116, name: "Purchase Gricoller's Can", task: "Purchase Gricoller's can from the Tithe Farm minigame.", skills: { farming: 34 }, location: null },
    { id: 117, name: "Purchase a Seed Box", task: "Purchase a Seed box from the Tithe Farm minigame.", skills: { farming: 34 }, location: null },
    { id: 118, name: "Equip a Pearl Fishing Rod", task: "Equip a Pearl fishing rod, purchased from Alry on Molch Island.", skills: {  }, location: null },
    { id: 119, name: "Equip a Pearl Barbarian Rod", task: "Equip a Pearl barbarian rod, purchased from Alry on Molch Island.", skills: {  }, location: null },
    { id: 120, name: "Equip a Brimstone Ring", task: "Obtain and equip a Brimstone ring.", skills: { slayer: 95 }, location: null }
  ];

  export const LeagueTaskArrayHard: LeagueTask[] = [
    { id: 2, name: "25 Hard Clue Scrolls", task: "Open 25 reward caskets for completing hard clue scrolls.", skills: {  }, location: null },
    { id: 3, name: "50 Hard Clue Scrolls", task: "Open 50 reward caskets for completing hard clue scrolls.", skills: {  }, location: null },
    { id: 4, name: "10 Elite Clue Scrolls", task: "Open 10 reward caskets for completing elite clue scrolls.", skills: {  }, location: null },
    { id: 5, name: "25 Elite Clue Scrolls", task: "Open 25 reward caskets for completing elite clue scrolls.", skills: {  }, location: null },
    { id: 6, name: "1 Master Clue Scroll", task: "Open a reward casket for completing a master clue scroll.", skills: {  }, location: null },
    { id: 7, name: "Complete a Drake Task", task: "Receive and complete a Drake slayer task.", skills: { slayer: 84 }, location: null },
    { id: 8, name: "250 Easy Clue Scrolls", task: "Open 250 reward caskets for completing easy clue scrolls.", skills: {  }, location: null },
    { id: 9, name: "100 Medium Clue Scrolls", task: "Open 100 reward caskets for completing medium clue scrolls.", skills: {  }, location: null },
    { id: 10, name: "250 Medium Clue Scrolls", task: "Open 250 reward caskets for completing medium clue scrolls.", skills: {  }, location: null },
    { id: 11, name: "1 Mimic Kill", task: "Kill the Mimic as part of a treasure trail.", skills: {  }, location: null },
    { id: 12, name: "5 Mimic Kills", task: "Kill the Mimic as part of a treasure trail 5 times.", skills: {  }, location: null },
    { id: 13, name: "1500 Total Level", task: "Reach a total level of 1500.", skills: { overall: 1500 }, location: null },
    { id: 14, name: "1750 Total Level", task: "Reach a total level of 1750.", skills: { overall: 1750 }, location: null },
    { id: 15, name: "Base Level 60", task: "Reach a minimum of level 60 across all of your skills.", skills: { overall: 60 }, location: null },
    { id: 16, name: "Base Level 70", task: "Reach a minimum of level 70 across all of your skills.", skills: { overall: 70 }, location: null },
    { id: 17, name: "Level 80 Attack", task: "Reach level 80 in your Attack skill.", skills: { attack: 80 }, location: null },
    { id: 18, name: "Level 80 Strength", task: "Reach level 80 in your Strength skill.", skills: { strength: 80 }, location: null },
    { id: 19, name: "Level 80 Defence", task: "Reach level 80 in your Defence skill.", skills: { defence: 80 }, location: null },
    { id: 20, name: "Level 80 Ranged", task: "Reach level 80 in your Ranged skill.", skills: { ranged: 80 }, location: null },
    { id: 21, name: "Level 80 Prayer", task: "Reach level 80 in your Prayer skill.", skills: { prayer: 80 }, location: null },
    { id: 22, name: "Level 80 Magic", task: "Reach level 80 in your Magic skill.", skills: { magic: 80 }, location: null },
    { id: 23, name: "Level 80 Runecraft", task: "Reach level 80 in your Runecraft skill.", skills: { runecraft: 80 }, location: null },
    { id: 24, name: "Level 80 Construction", task: "Reach level 80 in your Construction skill.", skills: { construction: 80 }, location: null },
    { id: 25, name: "Level 80 Hitpoints", task: "Reach level 80 in your Hitpoints skill.", skills: { hitpoints: 80 }, location: null },
    { id: 26, name: "Level 80 Agility", task: "Reach level 80 in your Agility skill.", skills: { agility: 80 }, location: null },
    { id: 27, name: "Level 80 Herblore", task: "Reach level 80 in your Herblore skill.", skills: { herblore: 80 }, location: null },
    { id: 28, name: "Level 80 Thieving", task: "Reach level 80 in your Thieving skill.", skills: { thieving: 80 }, location: null },
    { id: 29, name: "Level 80 Crafting", task: "Reach level 80 in your Crafting skill.", skills: { crafting: 80 }, location: null },
    { id: 30, name: "Level 80 Fletching", task: "Reach level 80 in your Fletching skill.", skills: { fletching: 80 }, location: null },
    { id: 31, name: "Level 80 Slayer", task: "Reach level 80 in your Slayer skill.", skills: { slayer: 80 }, location: null },
    { id: 32, name: "Level 80 Hunter", task: "Reach level 80 in your Hunter skill.", skills: { hunter: 80 }, location: null },
    { id: 33, name: "Level 80 Mining", task: "Reach level 80 in your Mining skill.", skills: { mining: 80 }, location: null },
    { id: 34, name: "Level 80 Smithing", task: "Reach level 80 in your Smithing skill.", skills: { smithing: 80 }, location: null },
    { id: 35, name: "Level 80 Fishing", task: "Reach level 80 in your Fishing skill.", skills: { fishing: 80 }, location: null },
    { id: 36, name: "Level 80 Cooking", task: "Reach level 80 in your Cooking skill.", skills: { cooking: 80 }, location: null },
    { id: 37, name: "Level 80 Firemaking", task: "Reach level 80 in your Firemaking skill.", skills: { firemaking: 80 }, location: null },
    { id: 38, name: "Level 80 Woodcutting", task: "Reach level 80 in your Woodcutting skill.", skills: { woodcutting: 80 }, location: null },
    { id: 39, name: "Level 80 Farming", task: "Reach level 80 in your Farming skill.", skills: { farming: 80 }, location: null },
    { id: 40, name: "200 Slayer Tasks", task: "Receive and complete a total of 200 slayer tasks.", skills: { other: "5 Combat" }, location: null },
    { id: 41, name: "300 Slayer Tasks", task: "Receive and complete a total of 300 slayer tasks.", skills: { other: "5 Combat" }, location: null },
    { id: 42, name: "400 Slayer Tasks", task: "Receive and complete a total of 400 slayer tasks.", skills: { other: "5 Combat" }, location: null },
    { id: 43, name: "500 Slayer Tasks", task: "Receive and complete a total of 500 slayer tasks.", skills: { other: "5 Combat" }, location: null },
    { id: 44, name: "Plant 100 Bologano Seeds", task: "Plant 100 Bologano seeds in the Tithe Farm minigame.", skills: { farming: 54 }, location: null },
    { id: 45, name: "Enter the Farming Guild's Mid Tier", task: "Enter the mid tier of the Farming Guild in the Kebos Lowlands.", skills: { farming: 65 }, location: null },
    { id: 46, name: "Serve 20 Pizzas in the Mess Hall", task: "Make and serve 20 pineapple pizzas in the Mess Hall in Hosidius. Note: This requires at least 30% appreciation.", skills: { cooking: 65 }, location: null },
    { id: 47, name: "Obtain Adamantite Ore at the Blast Mine", task: "Obtain a piece of Adamantite ore while taking part in the Blast Mine.", skills: { mining: 60 }, location: null },
    { id: 48, name: "Chop a Magic Log at the Forsaken Tower", task: "Chop a log from the Magic trees around the Forsaken Tower.", skills: { woodcutting: 75 }, location: null },
    { id: 49, name: "Cast Resurrect Crops", task: "Cast the spell Resurrect Crops from the Arceuus spellbook.", skills: { magic: 78 }, location: null },
    { id: 50, name: "Complete an Abyssal Demon Task", task: "Receive and complete an Abyssal Demon slayer task.", skills: { slayer: 85 }, location: null },
    { id: 51, name: "Complete a Hydra Task", task: "Receive and complete a Hydra slayer task.", skills: { slayer: 95 }, location: null },
    { id: 52, name: "150 Superior Slayer Encounters", task: "Defeat 150 superior foes while on a slayer task.", skills: { slayer: 15 }, location: null },
    { id: 53, name: "200 Superior Slayer Encounters", task: "Defeat 200 superior foes while on a slayer task.", skills: { slayer: 15 }, location: null },
    { id: 54, name: "250 Superior Slayer Encounters", task: "Defeat 250 superior foes while on a slayer task.", skills: { slayer: 15 }, location: null },
    { id: 55, name: "2500 Lizardmen Shaman Kills", task: "Help the Shayzien house by killing 2500 Lizardmen shamans.", skills: { slayer: 1 }, location: null },
    { id: 56, name: "5000 Lizardmen Shaman Kills", task: "Help the Shayzien house by killing 5000 Lizardmen shamans.", skills: { slayer: 1 }, location: null },
    { id: 57, name: "500 Sarachnis Kills", task: "Kill Sarachnis in the Forthos Dungeon 500 times.", skills: {  }, location: null },
    { id: 58, name: "10 Skotizo Kills", task: "Kill Skotizo beneath the Catacombs of Kourend 10 times.", skills: {  }, location: null },
    { id: 59, name: "1 Chambers of Xeric", task: "Complete the Chambers of Xeric.", skills: {  }, location: null },
    { id: 60, name: "25 Chambers of Xeric", task: "Complete the Chambers of Xeric 25 times.", skills: {  }, location: null },
    { id: 61, name: "50 Chambers of Xeric", task: "Complete the Chambers of Xeric 50 times.", skills: {  }, location: null },
    { id: 62, name: "75 Chambers of Xeric", task: "Complete the Chambers of Xeric 75 times.", skills: {  }, location: null },
    { id: 63, name: "100 Chambers of Xeric", task: "Complete the Chambers of Xeric 100 times.", skills: {  }, location: null },
    { id: 64, name: "1 CM Chambers of Xeric", task: "Complete the Chambers of Xeric Challenge Mode.", skills: {  }, location: null },
    { id: 65, name: "10 CM Chambers of Xeric", task: "Complete the Chambers of Xeric Challenge Mode 10 times.", skills: {  }, location: null },
    { id: 66, name: "Receive 1 Chambers of Xeric Unique", task: "Receive a unique drop from completing the Chambers of Xeric.", skills: {  }, location: null },
    { id: 67, name: "Equip a Dragon Warhammer", task: "Obtain and equip a Dragon warhammer.", skills: { attack: 60 }, location: null },
    { id: 68, name: "Equip a Dragonfire Shield", task: "Obtain and equip a Dragonfire shield.", skills: { defence: 75, smithing: 90 }, location: null },
    { id: 69, name: "Equip Boots of Brimstone", task: "Obtain and equip a pair of Boots of brimstone.", skills: { defence: 70, ranged: 70, magic: 70, slayer: 84 }, location: null },
    { id: 70, name: "Equip a Dust Battlestaff", task: "Obtain and equip a Dust battlestaff.", skills: { attack: 30, magic: 30 }, location: null },
    { id: 71, name: "Equip a Mist Battlestaff", task: "Obtain and equip a Mist battlestaff.", skills: { attack: 30, magic: 30 }, location: null },
    { id: 72, name: "Kourend and Kebos Hard Diary Tasks", task: "Complete all tasks in the hard tier of the Kourend and Kebos achievement diary.", skills: { other: "See here" }, location: null },
    { id: 73, name: "Open 100 Grubby Chests", task: "Open the grubby chest in the Forthos Dungeon 100 times.", skills: { thieving: 57 }, location: null },
    { id: 74, name: "Steal 250 Artefacts", task: "Steal 250 artefacts for Captain Khaled, in Piscarilius.", skills: { thieving: 49 }, location: null },
    { id: 75, name: "Equip the Farmer's Outfit", task: "Equip a full set of the farmer's outfit, purchased from the Tithe Farm minigame.", skills: { farming: 34 }, location: null },
    { id: 76, name: "Equip the Angler's Outfit", task: "Equip a full set of the angler's outfit, purchased from Alry on Molch Island.", skills: { fishing: 43, hunter: 35 }, location: null },
    { id: 77, name: "Equip the Pyromancer's Garb", task: "Equip a full set of pyromancer's garb, rewarded from the Wintertodt.", skills: {  }, location: null },
    { id: 78, name: "1000 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 1000 times.", skills: { firemaking: 50 }, location: null },
    { id: 79, name: "1500 Wintertodt Kills", task: "Help the pyromancers subdue the Wintertodt 1500 times.", skills: { firemaking: 50 }, location: null },
    { id: 80, name: "Complete 1000 Farming Contracts", task: "Complete 1000 farming contracts for Guildmaster Jane in the farming guild.", skills: { farming: 45 }, location: null },
    { id: 81, name: "1000 Sarachnis Kills", task: "Kill Sarachnis in the Forthos Dungeon 1000 times.", skills: {  }, location: null },
    { id: 82, name: "1500 Sarachnis Kills", task: "Kill Sarachnis in the Forthos Dungeon 1500 times.", skills: {  }, location: null },
    { id: 83, name: "250 Alchemical Hydra Kills", task: "Kill the Alchemical Hydra in Mount Karuulm 250 times.", skills: { slayer: 95 }, location: null },
    { id: 84, name: "500 Alchemical Hydra Kills", task: "Kill the Alchemical Hydra in Mount Karuulm 500 times.", skills: { slayer: 95 }, location: null },
    { id: 85, name: "1000 Alchemical Hydra Kills", task: "Kill the Alchemical Hydra in Mount Karuulm 1000 times.", skills: { slayer: 95 }, location: null },
    { id: 86, name: "1500 Alchemical Hydra Kills", task: "Kill the Alchemical Hydra in Mount Karuulm 1500 times.", skills: { slayer: 95 }, location: null },
    { id: 87, name: "Equip Ferocious Gloves", task: "Obtain and equip a pair of Ferocious gloves.", skills: { attack: 80, defence: 80, slayer: 95 }, location: null },
    { id: 88, name: "Turn in 500 Library Books", task: "Find and turn in 500 books in the Arceuus Library.", skills: {  }, location: null },
  ];

  export const LeagueTaskArrayElite: LeagueTask[] = [
    { id: 3000, name: "2000 Total Level", task: "Reach a total level of 2000.", skills: { overall: 2000 }, location: null },
    { id: 3001, name: "Equip an Eternal Slayer Ring", task: "Craft and equip an Eternal slayer ring.", skills: { crafting: 75 }, location: LeagueLocations.Asgarnia },
    { id: 3002, name: "Equip an Dragon Hunter Lance", task: "Obtain and equip a Dragon Huntert Lance.", skills: { attack: 70, slayer: 95 }, location: LeagueLocations.Fremennik }
  ];

  export const LeagueTaskArrayMaster: LeagueTask[] = [
    { id: 4000, name: "2277 Total Level", task: "Reach a total level of 2277.", skills: { overall: 2277 }, location: null },
    { id: 4001, name: "Equip a Golden Tench", task: "Equip a Golden tench, caught by aerial fishing on Molch Island.", skills: { hunter: 35, fishing: 43 }, location: LeagueLocations.Misthalin },
    { id: 4002, name: "Equip a Kodai Wand", task: "Obtain and equip a Kodai wand.", skills: { magic: 75 }, location: LeagueLocations.Karamja }
  ];
  